language: php
os: linux

php:
  - 7.3
  - 7.4
  - master

env:
  - DEPS="LOW"
  - DEPS="NORMAL"

addons:
  apt:
    packages:
      - acl
      - python-docutils

cache:
  directories:
    - $HOME/.composer/cache
    - build/cache

stages:
  - composer validate
  - test

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv rehash
  - set -e
  - composer self-update
  - composer global require hirak/prestissimo

install:
  - |
    if [[ "$DEPS" == "LOW" ]]; then
      composer install --prefer-dist --no-progress --no-interaction --no-suggest;
      composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --prefer-lowest;
    else
      composer install --optimize-autoloader --prefer-dist --no-progress --no-interaction --no-suggest;
    fi

script:
  - vendor/bin/phpunit

jobs:
  allow_failures:
    - php: 7.4
    - php: master
    - php: nightly
  include:
    - php: nightly
      env: DEPS="IGNORE"
      install: composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction --no-suggest --ignore-platform-reqs

    - stage: composer validate
      php: 7.3
      env: DEPS="NORMAL"
      script:
        - composer validate
